import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopBar from "./components/TopBar";
<<<<<<< HEAD
import Header from "./components/Header";
import Footer from "./components/Footer";
=======
import Footer from "./components/Footer";
import Header from "./components/Header";
>>>>>>> 4160730 (uiuxhackathon)

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <TopBar/>
<<<<<<< HEAD
 
 <Header />

{/* Main Content Area */}
<main>{children}</main>

{/* Footer Component */}
<Footer />
       
=======
      <Header/>
      
        <main>{children}</main>

       <Footer/>
>>>>>>> 4160730 (uiuxhackathon)
      </body>
    </html>
  );
}
